# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160421_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnus',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.AddField(
            model_name='alumnus',
            name='picture',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
