# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160421_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnus',
            name='workplace',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Workplace',
        ),
    ]
