# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_workplace'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workplace',
        ),
    ]
